#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Eloquent\Asplode\Asplode;
use Icecave\Overpass\Amqp\PubSub\AmqpSubscriber;
use Icecave\Stump\Logger;
use PhpAmqpLib\Connection\AMQPStreamConnection;

Asplode::install();

// Parse the command line parameters ...
list(, $sleep, $topic, $server, $port, $username, $password, $vhost) = $_SERVER['argv'] + [
    null,
    0,
    'default-topic',
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
];

// Connect to the AMQP server ...
$connection = new AMQPStreamConnection($server, $port, $username, $password, $vhost);

// Create an Overpass subscriber ...
$subscriber = new AmqpSubscriber($connection->channel());
$subscriber->setLogger(new Logger());

// Consume messages forver ...
$subscriber->subscribe($topic);
$subscriber->consume(
    function ($topic, $payload) use ($sleep) {
        usleep($sleep * 1000000);

        return true; // Instructs the subscriber to continue consuming.
    }
);
