#!/usr/bin/env php
<?php
// Initialize the AMQP connection, logger, etc.
require __DIR__ . '/common.php';

// Parse the command line parameters ...
list(, $sleep, $topic) = $_SERVER['argv'] + [
    null,
    0,               // sleep
    'default-topic', // topic
];

// Create an Overpass subscriber ...
$subscriber = new Icecave\Overpass\Amqp\PubSub\AmqpSubscriber(
    $amqpChannel
);

$subscriber->setLogger($logger);

// Consume messages forver ...
$subscriber->subscribe($topic);
$subscriber->consume(
    function ($topic, $payload) use ($sleep) {
        usleep($sleep * 1000000);

        return true; // Instructs the subscriber to continue consuming.
    }
);
