#!/usr/bin/env php
<?php
/**
 * Initialize the logger and AMQP connection.
 */
require __DIR__ . '/common.php';

/**
 * Parse the command line parameters.
 *
 * sleep: Number of seconds to wait between consuming messages.
 * topic: The topic to which messages are published.
 */
list(, $sleep, $topic) = $_SERVER['argv'] + [
    null,
    0,               // sleep
    'default-topic', // topic
];

/**
 * Create an Overpass subscriber.
 *
 * The subscriber is configured to subscribe to one or more topics and then
 * consume messages from thos topics.
 */
$subscriber = new Icecave\Overpass\Amqp\PubSub\AmqpSubscriber(
    $amqpChannel
);

$subscriber->setLogger($logger);
$subscriber->subscribe($topic);

/**
 * Consume messages forever!
 */
$subscriber->consume(
    function ($topic, $payload) use ($sleep) {
        usleep($sleep * 1000000);

        return true; // Instructs the subscriber to continue consuming.
    }
);
