#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Icecave\Overpass\Amqp\PubSub\AmqpPublisher;
use PhpAmqpLib\Connection\AMQPStreamConnection;

$connection = new AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
);

$topic = isset($_SERVER['argv'][1])
        ? $_SERVER['argv'][1]
        : 'default-topic';

$publisher = new AmqpPublisher(
    $connection->channel()
);

$payloadCounter = 1;

while (true) {
    $publisher->publish(
        $topic,
        (object) [ 'counter' => $payloadCounter++ ]
    );

    printf('==> %s %s' . PHP_EOL, $topic, $payloadCounter);

    usleep(10000);
}
