#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Icecave\Overpass\Amqp\PubSub\AmqpSubscriber;
use PhpAmqpLib\Connection\AMQPStreamConnection;

$connection = new AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
);

$subscriber = new AmqpSubscriber(
    $connection->channel()
);

$subscriber->subscribe(
    isset($_SERVER['argv'][1])
        ? $_SERVER['argv'][1]
        : '*'
);

$subscriber->consume(
    function ($topic, $payload) {
        printf('<== %s %s' . PHP_EOL, $topic, $payload->counter);

        return true;
    }
);
