#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Eloquent\Asplode\Asplode;
use Icecave\Overpass\Amqp\PubSub\AmqpPublisher;
use PhpAmqpLib\Connection\AMQPStreamConnection;

Asplode::install();

$connection = new AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
);

$topic = isset($_SERVER['argv'][1])
        ? $_SERVER['argv'][1]
        : 'default-topic';

$sleep = isset($_SERVER['argv'][2])
        ? $_SERVER['argv'][2]
        : 10000;

$publisher = new AmqpPublisher(
    $connection->channel()
);

$payloadCounter = 1;

while (true) {
    $publisher->publish(
        $topic,
        (object) [ 'counter' => $payloadCounter++ ]
    );

    printf('[publisher] ==> %s %s' . PHP_EOL, $topic, $payloadCounter);

    usleep($sleep);
}
