#!/usr/bin/env php
<?php
// Initialize the AMQP connection, logger, etc.
require __DIR__ . '/common.php';

// Create an Overpass RPC server ...
$server = new Icecave\Overpass\Amqp\Rpc\AmqpRpcServer(
    $logger,
    $amqpChannel
);

$server->expose(
    'double',
    function ($value) {
        return $value * 2;
    }
);

// Service RPC requests forever ...
$server->run();
