#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Icecave\Overpass\Amqp\Rpc\AmqpRpcServer;
use PhpAmqpLib\Connection\AMQPStreamConnection;

$connection = new AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
);

$server = new AmqpRpcServer(
    $connection->channel()
);

$server->register(
    'double',
    function ($value) {
        $result = $value * 2;
        printf('<== %s * 2 = %s' . PHP_EOL, $value, $result);

        return $value;
    }
);

$server->run();
