#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Eloquent\Asplode\Asplode;
use Icecave\Overpass\Amqp\Rpc\AmqpRpcServer;
use Icecave\Stump\Logger;
use PhpAmqpLib\Connection\AMQPStreamConnection;

Asplode::install();

// Parse the command line parameters ...
list(, $server, $port, $username, $password, $vhost) = $_SERVER['argv'] + [
    null,
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
];

// Connect to the AMQP server ...
$connection = new AMQPStreamConnection($server, $port, $username, $password, $vhost);

// Create an Overpass RPC server ...
$server = new AmqpRpcServer(new Logger(), $connection->channel());
$server->expose(
    'double',
    function ($value) {
        return $value * 2;
    }
);

// Service RPC requests forever ...
$server->run();
