#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Eloquent\Asplode\Asplode;
use Icecave\Overpass\Amqp\Rpc\AmqpRpcClient;
use PhpAmqpLib\Connection\AMQPStreamConnection;

Asplode::install();

$connection = new AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
);

$sleep = isset($_SERVER['argv'][1])
        ? $_SERVER['argv'][1]
        : 1000000;

$client = new AmqpRpcClient(
    $connection->channel()
);

$value = 0;

while (true) {
    printf('[client] ==> double(%d)' . PHP_EOL, $value++);

    $result = $client->double($value);

    printf('[client] <== %s' . PHP_EOL, $result);

    usleep($sleep);
}
