#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Eloquent\Asplode\Asplode;
use Icecave\Overpass\Amqp\Rpc\AmqpRpcClient;
use PhpAmqpLib\Connection\AMQPStreamConnection;

Asplode::install();

$connection = new AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/'
);

$client = new AmqpRpcClient(
    $connection->channel()
);

$value = 0;

while (true) {
    $value++;
    printf('[client] ==> double(%d)' . PHP_EOL, $value);
    $result = $client->double($value);
    printf('[client] <== %s' . PHP_EOL, $result);
    sleep(1);
}
