var tree = [["Icecave",,"",
                [["Overpass","Icecave\/Overpass.html","",
                [["Amqp","Icecave\/Overpass\/Amqp.html","",
                [["PubSub","Icecave\/Overpass\/Amqp\/PubSub.html","",
                [["AmqpPublisher","Icecave\/Overpass\/Amqp\/PubSub\/AmqpPublisher.html","",
                [        ]],["AmqpSubscriber","Icecave\/Overpass\/Amqp\/PubSub\/AmqpSubscriber.html","",
                [        ]],["DeclarationManager","Icecave\/Overpass\/Amqp\/PubSub\/DeclarationManager.html","",
                [        ]]        ]],["Rpc","Icecave\/Overpass\/Amqp\/Rpc.html","",
                [["AmqpRpcClient","Icecave\/Overpass\/Amqp\/Rpc\/AmqpRpcClient.html","",
                [        ]],["AmqpRpcServer","Icecave\/Overpass\/Amqp\/Rpc\/AmqpRpcServer.html","",
                [        ]],["DeclarationManager","Icecave\/Overpass\/Amqp\/Rpc\/DeclarationManager.html","",
                [        ]]        ]],["ChannelDispatcher","Icecave\/Overpass\/Amqp\/ChannelDispatcher.html","",
                [        ]]        ]],["PubSub","Icecave\/Overpass\/PubSub.html","",
                [["PublisherInterface","Icecave\/Overpass\/PubSub\/PublisherInterface.html","",
                [        ]],["SubscriberInterface","Icecave\/Overpass\/PubSub\/SubscriberInterface.html","",
                [        ]]        ]],["Rpc","Icecave\/Overpass\/Rpc.html","",
                [["Exception","Icecave\/Overpass\/Rpc\/Exception.html","",
                [["ExecutionException","Icecave\/Overpass\/Rpc\/Exception\/ExecutionException.html"," < Exception",
                [        ]],["InvalidArgumentsException","Icecave\/Overpass\/Rpc\/Exception\/InvalidArgumentsException.html"," < InvalidArgumentException",
                [        ]],["InvalidMessageException","Icecave\/Overpass\/Rpc\/Exception\/InvalidMessageException.html"," < LogicException",
                [        ]],["RemoteExceptionInterface","Icecave\/Overpass\/Rpc\/Exception\/RemoteExceptionInterface.html","",
                [        ]],["TimeoutException","Icecave\/Overpass\/Rpc\/Exception\/TimeoutException.html"," < RuntimeException",
                [        ]],["UnknownProcedureException","Icecave\/Overpass\/Rpc\/Exception\/UnknownProcedureException.html"," < LogicException",
                [        ]]        ]],["Message","Icecave\/Overpass\/Rpc\/Message.html","",
                [["MessageSerialization","Icecave\/Overpass\/Rpc\/Message\/MessageSerialization.html","",
                [        ]],["MessageSerializationInterface","Icecave\/Overpass\/Rpc\/Message\/MessageSerializationInterface.html","",
                [        ]],["Request","Icecave\/Overpass\/Rpc\/Message\/Request.html","",
                [        ]],["Response","Icecave\/Overpass\/Rpc\/Message\/Response.html","",
                [        ]],["ResponseCode","Icecave\/Overpass\/Rpc\/Message\/ResponseCode.html"," < AbstractEnumeration",
                [        ]]        ]],["Invoker","Icecave\/Overpass\/Rpc\/Invoker.html","",
                [        ]],["InvokerInterface","Icecave\/Overpass\/Rpc\/InvokerInterface.html","",
                [        ]],["RpcClientInterface","Icecave\/Overpass\/Rpc\/RpcClientInterface.html","",
                [        ]],["RpcServerInterface","Icecave\/Overpass\/Rpc\/RpcServerInterface.html","",
                [        ]]        ]],["Serialization","Icecave\/Overpass\/Serialization.html","",
                [["Exception","Icecave\/Overpass\/Serialization\/Exception.html","",
                [["SerializationException","Icecave\/Overpass\/Serialization\/Exception\/SerializationException.html"," < InvalidArgumentException",
                [        ]]        ]],["JsonSerialization","Icecave\/Overpass\/Serialization\/JsonSerialization.html","",
                [        ]],["SerializationInterface","Icecave\/Overpass\/Serialization\/SerializationInterface.html","",
                [        ]]        ]],["PackageInfo","Icecave\/Overpass\/PackageInfo.html","",
                [        ]]        ]]        ]]        ]

